touch c:\jdubb\workspaces\subjects\subjnew6\fw//.fw_all_start
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s1
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s2
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s3
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s4
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s5
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s6
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s7
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s8
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s9
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s10
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s11
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s12
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.s13
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d1
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d2
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d3
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d4
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d5
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d6
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d7
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d8
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d9
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d10
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d11
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d12
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d13
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d14
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d15
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d16
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d17
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d18
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d19
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d20
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d21
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d22
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d23
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d24
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d25
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d26
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d27
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d28
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d29
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d30
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d31
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d32
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d33
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d34
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d35
c:/users/jdubb/desktop/tMCimg/bin/Win/tMCimg.exe  c:\jdubb\workspaces\subjects\subjnew6\fw/fw1.d36
touch c:\jdubb\workspaces\subjects\subjnew6\fw//.fw_all_stop
